### ISSUE TITLE
TPCC Population Issues on IO Branch

### ISSUE THREAD

**Issue by cdcsl** [leanstore/leanstore#13]
Hi there,

When trying to populate TPCC with the following command

`tpcc --ssd_path=/mnt/dbs/tpcc --worker_threads=36 --pp_threads=4 --dram_gib=16 --tpcc_warehouse_count=1000 --notpcc_warehouse_affinity --csv_path=./log --cool_pct=40 --free_pct=1 --contention_split --xmerge --print_tx_console --run_until_tx=10000000 `

I hit either a SIGSEGV at PageGuard.hpp:212

`inline T* operator->() { return reinterpret_cast<T*>(ref_guard.bf->page.dt); }`

It seems that the ref_guard is corrupt, as I'm unable to print `ref_guard.bf` in gdb.

Or an assertion failure at BTreeGeneric.cpp:343

`assert(from_left->compareKeyWithBoundaries(new_left_uf_key, new_left_uf_length) == 0);`

Leanstore is going out of memory at both points.

Also, the out-of-memory load performance seems to be low, at around 25 mb/s on a fast disk and a 40 core system.

I was wondering if the errors had been spotted before, and if so, is there some way to fix them? Also, if possible, I was wondering if there is some way to speed up the initial insert.

Thanks.

**Comment by gabriel-haas** [comment]
Hi there,

there was an issue with xmerge and contention split in this branch. This should be fixed now. I added a better example on how to use the branch in the Readme.

Best regards,
Gabriel

**Comment by cdcsl** [comment]
@gabriel-haas Thanks for your help, seems to be working great.

If I may add, build/vendor/spdk/src/spdk-ext/scripts/setup.sh needs to be run before the SPDK test.

**Comment by gabriel-haas** [comment]
You’re right, thanks, I added a note about the spdk setup.
