### ISSUE TITLE
paper implementation exists in this repo ?

### ISSUE THREAD

**Issue by baiwfg2** [leanstore/leanstore#6]
Hi. Recently I'm reading paper "rethinking logging checkpoints and recovery for high-performance storage engines" (https://db.in.tum.de/~leis/papers/rethinkingLogging.pdf)

I'm wondering the implementation in the paper exists in this repo. Anyone knows it ?

**Comment by baiwfg2** [comment]
@adnan-alhomssi Hi, is this repo being developed ? Accept any PR ? I'm very interested in leanstore implementation.

**Comment by adnan-alhomssi** [comment]
@baiwfg2 Yes but on a rather slow pace. We will update this repository once the related research is accepted or published.
It depends on the PR, you can email me with your idea if you have something in mind.

**Comment by adnan-alhomssi** [comment]
@baiwfg2 FYI: I have merged the snapshot isolation implementation in master. The design is described in the coming VLDB paper "Scalable and Robust Snapshot Isolation for High-Performance Storage Engines"

**Comment by GavinRay97** [comment]
I also came here hoping to get an understanding of how to implement the recovery algorithm from the mentioned paper.

Thanks a ton for maintaining the repo and making the code public. Will be on the lookout for that upcoming VLDB paper!
