### ISSUE TITLE
fatal error: wiredtiger.h: No such file or directory

### ISSUE THREAD

**Issue by Ingsuifon** [leanstore/leanstore#8]
When compiling, I get this problem, does it need the dependency of wiredtiger?

**Comment by adnan-alhomssi** [comment]
LeanStore itself does not depend on WiredTiger but we have benchmarks in our frontend directory that depends on it, namely these Make targets `wiredtiger_tpcc wiredtiger_ycsb`.
`make leanstore ycsb tpcc` should work it.
You can install the dependency on ubuntu using `libwiredtiger-dev`
